### ISSUE TITLE
Custodian  table uses uuid instead of string

### ISSUE THREAD

**Issue by user3470** [021-projects/laravel-wallet#9]
uuid fails when using with postgres 

`SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid:  "service_name"`

**Comment by 021-projects** [comment]
Hey! 
Fixed in https://github.com/021-projects/laravel-wallet/commit/d4d52b326d79f34063a74158ca6f7c0cf952f4f1
I think you have already found a solution for this situation, but if not, do not forget to update the migrations after updating the package. I apologize for the delay, the war in my country does not allow me to freely manage my time :(
